kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.resource.service.port }}
      protocol: {{ .Values.resource.service.protocol }}
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
  policyTypes:
  - Egress
  - Ingress
