apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: {{ .Values.resource.default.name }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releases
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releasecycles
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releases/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releasecycles/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - application.giantswarm.io
    resources:
      - apps
    verbs:
      - "*"
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.resource.default.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.resource.default.name }}
    namespace: {{ .Values.resource.default.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.resource.default.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.resource.psp.name }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ .Values.resource.psp.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.resource.psp.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.resource.default.name }}
    namespace: {{ .Values.resource.default.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.resource.psp.name }}
  apiGroup: rbac.authorization.k8s.io
