apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - release-operator-configmap
    verbs:
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-operator
subjects:
  - kind: ServiceAccount
    name: release-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: release-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - release-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-operator-psp
subjects:
  - kind: ServiceAccount
    name: release-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: release-operator-psp
  apiGroup: rbac.authorization.k8s.io
