apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releases
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releasecycles
    verbs:
      - "*"
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releases/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releasecycles/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - application.giantswarm.io
    resources:
      - apps
    verbs:
      - "*"
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-operator
subjects:
  - kind: ServiceAccount
    name: release-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: release-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - release-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-operator-psp
subjects:
  - kind: ServiceAccount
    name: release-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: release-operator-psp
  apiGroup: rbac.authorization.k8s.io
